[package]
name = "tokenizator-plus"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.8.0"
actix-files = "0.6.5"
tera = "1.19.1"
walkdir = "2.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.120"
glob = "0.3.1"
